spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memory
    username: postgres
    password: 1208
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.yandex.ru
    username: sweaterRu@yandex.ru
    password: sweaterRusweaterRu
    port: 465
    protocol: smtps

mail.debug: true
pathNameUpload: C:/Users/Sergey/Documents/projectApp/src/uploads
